--- 
title: "How well does the APBA baseball board game model reality?"
author: "Barbara Bettencourt, Gregor Hanuschak, Zicheng Huang"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

APBA (American Professional Baseball Association) baseball is a baseball board game that has been played by hardcore baseball fans for decades.  It touts itself as being extremely accurate and true-to-life.

APBA makes "cards" for every major league baseball player for every season of major league baseball.  These cards are based on real life statistics.  You play the game by rolling dice and looking at the result on the cards (simplified description of the game).  The game is accurate enough that adjustments are even made for how well players do against left or right-handed pitchers and even the particular baseball stadium you choose to play in (so similar numbers of homeruns should occur in each ballpark in the game as they do in real life).

We have access to many scoresheets of data from many times the board game was played (scorecards include how many at-bats players had in the game, how many hits they had, how many runs that pitchers gave up, etc.)

Our project idea is to compare statistics of how players do in the game versus how they did in real life.

As a simple example, if a player had 300 at-bats, and had 100 hits in real life then you would expect that the same player would have 50 hits in the game if he had 150 at-bats.

We will see how close to reality the modeling actually is in APBA baseball.